version: "1"
services:
  api:
    image: api:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - database.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - database.env
    networks:
      - postgres



networks:
  postgres:
    driver: bridge